security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    com:
      cumuluslab:
        mylab: DEBUG

greeting:
  displayFortune: true

quoteServiceURL: http://quote-service-dev.cfapps.io/quote
